#spring.application.name=bookommendBE
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookommend?characterEncoding=UTF-8&serverTimezone=UTC
    username: test
    password: test

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    host: smtp.naver.com
    port: 465 # 또는 587
    username: test
    password: test
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com
        debug: true # 필요에 따라 설정
logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG

naver:
  clientId:
    test
  secretId:
    test
  url: https://openapi.naver.com
  path: /v1/search/book.json

library:
  key:
    test
